baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Volundarhus"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Hunter Mills"
  info = "ML Engineer | Data Scientist | Mentor | Tinkerer"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/Hunter_Mills.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/huntermills707/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/hunter-mills"
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 3
  url = "mailto:hunter.mills@pm.me"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Publications"
  weight = 2
  url  = "publications/"
[[menu.main]]
  name = "Resume/CV"
  weight = 3
  url = "resume/"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about/"
